<div class="container">
    <h1 class="text-center">Goods</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
            <a href="/admin/goods/create" class="btn btn-primary">New</a>
        </div>
        <div class="col-md-8">
        </div>
        <div class="col-md-2">
            <a href="/admin/goodsgroup/list" target="_blank" class="btn btn-info">Group</a>
            <a href="/admin/goods/log" target="_blank" class="btn btn-warning">Log</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Price</th>
                    <th>Effect Trigger</th>
                    <th>Rarity</th>
                    <th>Status</th>
                    <th>&nbsp;</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><?=$row['id']?></td>
                        <td><?=Misc::escape($row['title'])?></td>
                        <td><?=$row['price']?></td>
                        <td><?=$row['effect_trigger']?></td>
                        <td><?=$row['rarity']?></td>
                        <td>
                            <?php if ($row['is_active']) { ?>
                                <span class="label label-success">Active</span>
                            <?php } else { ?>
                                <span class="label label-default">Inactive</span>
                            <?php } ?>
                        </td>
                        <td>
                            <a href="/admin/goods/update?id=<?=$row['id']?>" class="btn btn-primary btn-sm">Edit</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#selectAll").click(function() {
            var checked = $(this).prop("checked");

            $("input[name='ids']").prop("checked", checked);
        });

        $(".btn-delete").click(function() {
            return window.confirm('Really???');
        });
    });
</script>