<div class="container">
    <h1 class="text-center">Streaming History</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
            &nbsp;
        </div>
        <div class="col-md-10">
            <form class="form-inline" role="form" method="get" action="/admin/streamingchannel/history">
                <div class="form-group">
                    <label for="channel" class="control-label input-sm">Channel</label>
                    <input type="text" name="channel" id="channel" class="form-control input-sm" value="<?=isset($filter['channel']) ? $filter['channel'] : ''?>">
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th style="width: 100px;">Channel</th>
                    <th style="width: 200px;">From</th>
                    <th style="width: 200px;">To</th>
                    <th style="width: 120px;">Length</th>
                    <th>Log</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><?=Misc::escape($row['channel'])?></td>
                        <td><?=date('Y-m-d H:i (P)', $row['from'])?></td>
                        <td><?=$row['to'] ? date('Y-m-d H:i (P)', $row['to']) : '-'?></td>
                        <td><?=Misc::formatTimeLength($row['length'])?></td>
                        <td>
                            <button class="btn btn-default btn-xs btn-log" data-id="<?=$row['id']?>" data-channel="<?=$row['channel']?>" data-ip="<?=$row['upstream_ip']?>" data-session="<?=$row['session']?>" title="" data-toggle="popover" data-placement="auto">...</button>
                            <div style="overflow: auto; display: none;">
                                <pre id="log-<?=$row['id']?>">aaa</pre>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(function() {
        $(".btn-log").each(function() {
            $(this).click(function() {
                var btn = $(this);
                var pre = $("#log-" + btn.data("id"));

                if (btn.data('content') == undefined) {
                    $.post(
                        "/admin/streamingchannel/live_log",
                        {
                            channel: btn.data("channel"),
                            ip: btn.data("ip"),
                            session: btn.data("session")
                        },
                        function (response) {
                            if (response.code == 200) {
                                var content = "";
                                for (var i=0; i < response.data.length; i++) {
                                    content += "[" + response.data[i].timestamp + "] " + response.data[i].content + "\n";
                                }
                                btn.hide();
                                pre.text(content);
                                pre.parent().show();
                            }
                        },
                        "json"
                    );
                }
            });
        });
    });
</script>