<div class="modal fade" id="memo-modal" tabindex="-1" role="dialog" aria-labelledby="channel-memo" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="memoModalLabel">Memo</h4>
            </div>
            <div class="modal-body">
                <p>
                    <textarea id="input-channel-memo" name="input-channel-memo" class="form-control" rows="8"></textarea>
                </p>
                <input type="hidden" id="memo-channel" name="memo-channel" value="">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="save-memo">Save</button>
            </div>
        </div>
    </div>
</div>