<div class="container">
    <h1 class="text-center">Watching Lengths</h1>
    <br />
    <div class="row">
        <div class="col-md-12">
            <form class="form-inline" role="form" method="get" action="/admin/streamingchannel/watching_lengths">
                <div class="form-group">
                    <label for="channel" class="control-label input-sm">Channel</label>
                    <input type="text" name="channel" id="channel" class="form-control input-sm" value="<?=isset($filter['channel']) ? $filter['channel'] : ''?>">
                </div>
                <div class="form-group">
                    <label for="min-fragment" class="control-label input-sm">Min Fragment</label>
                    <input type="text" name="min_fragment" id="min-fragment" class="form-control input-sm" value="<?=isset($filter['min_fragment']) ? $filter['min_fragment'] : 60?>">
                </div>
                <div class="form-group">
                    <label for="from" class="control-label input-sm">From</label>
                    <input type="text" class="form-control input-sm" id="from" name="from" value="">
                </div>
                <div class="form-group">
                    <label for="to" class="control-label input-sm">To</label>
                    <input type="text" class="form-control input-sm" id="to" name="to" value="">
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>Channel ID</th>
                    <th>Lengths</th>
                    <th>Times</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr>
                        <td><?=Misc::escape($row['channel'])?></td>
                        <td><?=Misc::formatTimeLength($row['l'])?></td>
                        <td><?=$row['v']?></td>
                        <td>
                            &nbsp;
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#from").datepicker({
            changeMonth: true,
            dateFormat: "yy-mm-dd",
            onClose: function(selectedDate) {
                $("#to").datepicker("option", "minDate", selectedDate);
            }
        });

        $("#from").datepicker("setDate", "<?=isset($filter['from']) ? $filter['from'] : date('Y-m-d')?>");

        $("#to").datepicker({
            changeMonth: true,
            dateFormat: "yy-mm-dd",
            onClose: function(selectedDate) {
                $("#from").datepicker("option", "maxDate", selectedDate);
            }
        });

        $("#to").datepicker("setDate", "<?=isset($filter['to']) ? $filter['to'] : date('Y-m-d')?>");
    });
</script>