#!/bin/bash
php 1-parse-deck-list.php in=data/html/druid-1.html class=druid
php 1-parse-deck-list.php in=data/html/druid-2.html class=druid
php 1-parse-deck-list.php in=data/html/hunter-1.html class=hunter
php 1-parse-deck-list.php in=data/html/hunter-2.html class=hunter
php 1-parse-deck-list.php in=data/html/mage-1.html class=mage
php 1-parse-deck-list.php in=data/html/mage-2.html class=mage
php 1-parse-deck-list.php in=data/html/paladin-1.html class=paladin
php 1-parse-deck-list.php in=data/html/paladin-2.html class=paladin
php 1-parse-deck-list.php in=data/html/priest-1.html class=priest
php 1-parse-deck-list.php in=data/html/priest-2.html class=priest
php 1-parse-deck-list.php in=data/html/rogue-1.html class=rogue
php 1-parse-deck-list.php in=data/html/rogue-2.html class=rogue
php 1-parse-deck-list.php in=data/html/shaman-1.html class=shaman
php 1-parse-deck-list.php in=data/html/shaman-2.html class=shaman
php 1-parse-deck-list.php in=data/html/warlock-1.html class=warlock
php 1-parse-deck-list.php in=data/html/warlock-2.html class=warlock
php 1-parse-deck-list.php in=data/html/warrior-1.html class=warrior
php 1-parse-deck-list.php in=data/html/warrior-2.html class=warrior
