<div class="container">
    <h1 class="text-center">Show Image Request</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
            &nbsp;
        </div>
        <div class="col-md-10">
            <form class="form-inline" role="form" method="get" action="/admin/streamingrequest/list">
                <div class="form-group">
                    <label for="channel" class="control-label input-sm">Channel ID</label>
                    <input type="text" name="channel" id="channel" class="form-control input-sm" value="<?=isset($filter['channel']) ? $filter['channel'] : ''?>">
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Channel</th>
                    <th>Small</th>
                    <th>Large</th>
                    <th>Status</th>
                    <th>Created On</th>
                    <th>Processed On</th>
                    <th>&nbsp;</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><?=$row['id']?></td>
                        <td><?=$row['channel']?> (<?=Misc::escape($row['user_name'])?>)</td>
                        <td><?=$row['small_show_image'] ? 'Y' : ''?></td>
                        <td><?=$row['large_show_image'] ? 'Y' : ''?></td>
                        <td>
                            <?php if ($row['req_status'] == MySQL_Streaming_ShowImageRequestModel::REQ_STATUS_PENDING) { ?>
                                <span class="label label-default">Pending</span>
                            <?php } else if ($row['req_status'] == MySQL_Streaming_ShowImageRequestModel::REQ_STATUS_APPROVED) { ?>
                                <span class="label label-success">Approved</span>
                            <?php } else if ($row['req_status'] == MySQL_Streaming_ShowImageRequestModel::REQ_STATUS_DENIED) { ?>
                                <span class="label label-danger">Denied</span>
                            <?php } ?>
                        </td>
                        <td><?=date('Y-m-d H:i', $row['created_on'])?></td>
                        <td><?=$row['processed_on'] ? date('Y-m-d H:i', $row['processed_on']) : ''?></td>
                        <td>
                            <a href="/admin/streamingrequest/view?id=<?=$row['id']?>" class="btn btn-primary btn-sm" target="_blank">View</a>
                            <?php if ($row['req_status'] == MySQL_Streaming_ShowImageRequestModel::REQ_STATUS_PENDING) { ?>
                                <a href="/admin/streamingrequest/approve?id=<?=$row['id']?>" class="btn btn-info btn-sm btn-approve" data-id="<?=$row['id']?>">Approve</a>
                                <a href="/admin/streamingrequest/deny?id=<?=$row['id']?>" class="btn btn-danger btn-sm btn-deny" data-id="<?=$row['id']?>">Deny</a>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#selectAll").click(function() {
            var checked = $(this).prop("checked");

            $("input[name='ids']").prop("checked", checked);
        });

        $(".btn-approve").each(function() {
            $(this).click(function() {
                if (window.confirm('Really approve???')) {
                    var btn = $(this),
                        id  = btn.data("id");

                    $.post(
                        "/admin/streamingrequest/approve",
                        {
                            id: id
                        },
                        function(response) {
                            if (response.code == 200) {
                                window.alert(response.message);

                                window.location.reload();
                            } else {
                                window.alert(response.message ? response.message : "Failed");
                            }
                        },
                        "json"
                    );
                }

                return false;
            });
        });

        $(".btn-deny").each(function() {
            $(this).click(function() {
                if (window.confirm('Really deny???')) {
                    var btn = $(this),
                        id  = btn.data("id");

                    $.post(
                        "/admin/streamingrequest/deny",
                        {
                            id: id
                        },
                        function(response) {
                            window.location.reload();
                        },
                        "json"
                    );
                }

                return false;
            });
        });
    });
</script>