<div class="container">
    <h1 class="text-center">Edit Streaming Column</h1>
    <br />
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <form class="form-horizontal" role="form" method="post" action="/admin/streamingcolumnitem/<?=$action?>" enctype="multipart/form-data">
                <input type="hidden" name="id" id="id" value="<?=isset($id) ? $id : ''?>" />
                <div class="form-group">
                    <label for="column" class="col-sm-2 control-label">Column</label>
                    <div class="col-sm-10">
                        <select name="column" class="form-control input-sm">
                            <?php foreach ($columns as $key => $val) { ?>
                            <option value="<?=$key?>" <?=(isset($data['column']) && $key==$data['column']) ? 'selected="selected"' : ''?>><?=Misc::escape($val)?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="media_type" class="col-sm-2 control-label">Media Type</label>
                    <div class="col-sm-10">
                        <select name="media_type" class="form-control input-sm">
                            <?php foreach ($types as $val) { ?>
                                <option value="<?=$val?>" <?=(isset($data['media_type']) && $val==$data['media_type']) ? 'selected="selected"' : ''?>><?=$val?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="source" class="col-sm-2 control-label">Source</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="source" name="source" value="<?=isset($data['source']) ? Misc::escape($data['source']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="title" name="title" value="<?=isset($data['title']) ? Misc::escape($data['title']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="small_image" class="col-sm-2 control-label">Small Image</label>
                    <div class="col-sm-10">
                        <input type="file" class="form-control" id="small_image_file" name="small_image_file">
                        <?php if (isset($data['small_image']) && $data['small_image']) { ?>
                            <img src="<?=$data['small_image']?>" class="img-thumbnail" alt="#">
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label for="large_image" class="col-sm-2 control-label">Large Image</label>
                    <div class="col-sm-10">
                        <input type="file" class="form-control" id="large_image_file" name="large_image_file">
                        <?php if (isset($data['large_image']) && $data['large_image']) { ?>
                            <img src="<?=$data['large_image']?>" class="img-thumbnail" alt="#">
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label for="live_schedule_time" class="col-sm-2 control-label">Live Schedule Time</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="live_schedule_time" name="live_schedule_time" value="<?=isset($data['live_schedule_time']) ? $data['live_schedule_time'] : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="display_order" class="col-sm-2 control-label">Display Order</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="display_order" name="display_order" value="<?=isset($data['display_order']) ? Misc::escape($data['display_order']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="<?=$_SERVER['HTTP_REFERER'] ?: '/admin/streamingcolumnitem/list'?>" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>