<div class="container">
    <h1 class="text-center">Summoner Rank</h1>
    <br />
    <div class="row">
        <div class="col-md-12">
            <form class="form-inline" role="form" method="get" action="/admin/lolsummoner/rank">
                <div class="form-group">
                    <label for="platform" class="control-label input-sm">Platform</label>
                    <select name="platform" class="form-control input-sm">
                        <?php foreach ($platforms as $key => $val) { ?>
                            <option value="<?=$key?>" <?=(isset($filter['platform']) && (strcasecmp($key, $filter['platform']) === 0)) ? 'selected="selected"' : ''?>><?=strtoupper($key) . ' - ' . $val?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="champion" class="control-label input-sm">Champion</label>
                    <select name="champion" class="form-control input-sm">
                        <option value="">All</option>
                        <?php foreach ($champions as $key => $val) { ?>
                            <option value="<?=$key?>" <?=(isset($filter['champion']) && $key==$filter['champion']) ? 'selected="selected"' : ''?>><?=$val?></option>
                        <?php } ?>
                    </select>
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
    </div>
    <div class="row">
        <?php if (isset($paginator)) {?>
            <div class="col-md-12">
                <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
            </div>
        <?php } ?>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Summoner</th>
                    <th>Total matches</th>
                    <th>Win</th>
                    <th>Win rate</th>
                    <th>Killed</th>
                    <th>Deaths</th>
                    <th>Assists</th>
                    <th>Operation</th>
                </tr>
                </thead>
                <tbody>
                <?php
                if (isset($data)) { foreach ($data as $row) {
                    ?>
                    <tr>
                        <td><?=$row['rank']?></td>
                        <td><?=$row['id']?></td>
                        <td><?=$row['total_matches']?></td>
                        <td><?=$row['win']?></td>
                        <td><?=$row['win_rate']?></td>
                        <td><?=$row['k']?></td>
                        <td><?=$row['d']?></td>
                        <td><?=$row['a']?></td>
                        <td>
                            <a href="/admin/lolsummoner/view?platform=<?=$filter['platform']?>&summoner=<?=$row['id']?>" class="btn btn-primary btn-sm">View</a>
                        </td>
                    </tr>
                <?php }} ?>
                </tbody>
            </table>
        </div>
    </div>
</div>