<div class="container">
    <h1 class="text-center">View Summoner Info</h1>
    <br />
    <div class="row">
        <div class="col-md-12">
            <a href="/admin/lolsummoner/search" class="btn btn-primary">Search</a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <tr>
                    <th>ID</th>
                    <td><?=isset($data['id']) ? $data['id'] : ''?></td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td><?=isset($data['name']) ? Misc::escape($data['name']) : ''?></td>
                </tr>
                <tr>
                    <th>Level</th>
                    <td><?=isset($data['level']) ? $data['level'] : ''?></td>
                </tr>
                <tr>
                    <th>Profile Icon</th>
                    <td><?=isset($data['icon_id']) ? $data['icon_id'] : ''?></td>
                </tr>
                <tr>
                    <th>Time Until Next First Win Bonus</th>
                    <td><?=isset($data['tunfwb']) ? $data['tunfwb'] : ''?></td>
                </tr>
                <tr>
                    <th>Last MK User</th>
                    <td><?=isset($data['last_mk_user']) ? $data['last_mk_user'] : ''?></td>
                </tr>
                <tr>
                    <th>Summary</th>
                    <td>
                        <table class="table table-condensed">
                            <tr>
                                <th>Mode</th>
                                <th>Wins</th>
                                <th>Losses</th>
                                <th>Leaves</th>
                                <th>Tier</th>
                                <th>Rank</th>
                            </tr>
                            <?php if (isset($data['metadata'])) { foreach ($data['metadata'] as $key => $val) { ?>
                            <tr>
                                <th><?=Misc::escape($key)?></th>
                                <th><?=$val['wins']?></th>
                                <th><?=$val['losses']?></th>
                                <th><?=$val['leaves']?></th>
                                <th><?=$val['tier']?></th>
                                <th><?=$val['rank']?></th>
                            </tr>
                            <?php }} ?>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>