<div class="container">
    <h1 class="text-center">Red List</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
            <a href="/admin/red/publish" id="btn-publish" class="btn btn-warning">Publish Red</a>
        </div>
        <div class="col-md-6">
            <form class="form-inline" role="form" method="get" action="/admin/red/list">
                <div class="form-group">
                    <label for="user" class="control-label input-sm">User ID</label>
                    <input type="text" name="user" id="user" class="form-control input-sm" value="<?=isset($filter['user']) ? $filter['user'] : ''?>">
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
        <div class="col-md-4">
            <a href="/admin/redtype/list" id="btn-import" class="btn btn-primary">Red Types</a>
            <a href="/admin/red/schedules" id="btn-schedules" class="btn btn-info">View Schedules</a>
            <a href="/admin/red/summary" id="btn-summary" class="btn btn-success">Summary</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>User</th>
                    <th>Name</th>
                    <th>Points</th>
                    <th>Number</th>
                    <th>Created On</th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><?=$row['id']?></td>
                        <td><?=$row['user']?></td>
                        <td><?=Misc::escape($row['name'])?></td>
                        <td><?=$row['points']?></td>
                        <td><?=$row['number']?></td>
                        <td><?=$row['created_on'] ? date('Y-m-d H:i', $row['created_on']) : ''?></td>
                        <td>
                            <a href="/admin/red/view?id=<?=$row['id']?>" target="_blank" class="btn btn-primary btn-sm">View</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php include Yaf_View_Simple::getScriptPath() . DIRECTORY_SEPARATOR . 'red' . DIRECTORY_SEPARATOR . 'modal-publish.phtml'; ?>

<script>
    $(function() {
        $("#selectAll").click(function() {
            var checked = $(this).prop("checked");

            $("input[name='ids']").prop("checked", checked);
        });

        $("#btn-publish").click(function() {
            $.post(
                "/admin/point/balance",
                {},
                function(response) {
                    if (response.code == 200) {
                        $("#publish-current").val(response.data + "");

                        $("#publish-modal").modal("show");
                    }
                },
                "json"
            );

            return false;
        });

        $("#submit-publish").click(function() {
            var points = $("#publish-points").val(),
                number = $("#publish-number").val(),
                memo   = $("#publish-memo").val(),
                targetClient = $('input[name="publish-target-client"]:checked').val();

            $.post(
                "/admin/red/publish",
                {
                    points: points,
                    number: number,
                    memo: memo,
                    target_client: targetClient
                },
                function(response) {
                    if (response.code == 200) {
                        window.alert(response.message);

                        window.location.reload();
                    } else {
                        window.alert(response.message ? response.message : "Failed");
                    }
                },
                "json"
            );

            $("#publish-modal").modal("hide");
        });
    });
</script>