<div class="container">
    <h1 class="text-center">Red Summary</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
            <button class="btn btn-success disabled">Total Points <span class="badge"><?=$total_points?></span></button>
        </div>
        <div class="col-md-6">
            &nbsp;
        </div>
        <div class="col-md-4">
            &nbsp;
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Points</th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr>
                        <td><?=$row['dt']?></td>
                        <td><?=$row['points']?></td>
                        <td>
                            &nbsp;
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
