<div class="container">
    <h1 class="text-center">Edit Announcement</h1>
    <br />
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <form class="form-horizontal" role="form" method="post" action="/admin/announcement/<?=$action?>">
                <input type="hidden" name="id" id="id" value="<?=isset($data['id']) ? $data['id'] : ''?>" />
                <div class="form-group">
                    <label for="client" class="col-sm-2 control-label">Client</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="client" name="client" value="<?=isset($data['client']) ? Misc::escape($data['client']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="lang" class="col-sm-2 control-label">Lang</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="lang" name="lang" value="<?=isset($data['lang']) ? Misc::escape($data['lang']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">URL</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="url" name="url" value="<?=isset($data['url']) ? Misc::escape($data['url']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="/admin/announcement/list" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>