<div class="container">
    <h1 class="text-center">Announcement List</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
            <a href="/admin/announcement/create" class="btn btn-primary">New</a>
        </div>
        <div class="col-md-7">
            <form class="form-inline" role="form" method="get" action="/admin/announcement/list">
                <div class="form-group">
                    <label for="client" class="control-label input-sm">Client</label>
                    <select name="client" class="form-control input-sm">
                        <option value="">All</option>
                        <?php foreach ($clients as $val) { ?>
                            <option value="<?=$val?>" <?=(isset($filter['client']) && $val == $filter['client']) ? 'selected="selected"' : ''?>><?=$val?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="lang" class="control-label input-sm">Lang</label>
                    <select name="lang" class="form-control input-sm">
                        <option value="">All</option>
                        <?php foreach ($langs as $key => $val) { ?>
                            <option value="<?=$key?>" <?=(isset($filter['lang']) && $key==$filter['lang']) ? 'selected="selected"' : ''?>><?=$val?></option>
                        <?php } ?>
                    </select>
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Client</th>
                    <th>Lang</th>
                    <th>Url</th>
                    <th>Status</th>
                    <th>Published on</th>
                    <th>Operation</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><?=$row['id']?></td>
                        <td><?=$row['client']?></td>
                        <td><?=$row['lang']?></td>
                        <td><?=Misc::escape($row['url'])?></td>
                        <td><?=$row['status']?></td>
                        <td><?=$row['published_on'] ? date('Y-m-d H:i', $row['published_on']) : ''?></td>
                        <td>
                            <a href="/admin/announcement/update?id=<?=$row['id']?>" class="btn btn-primary btn-sm">Edit</a>
                            <a href="/admin/announcement/publish?id=<?=$row['id']?>" class="btn btn-danger btn-sm btn-delete" data-id="<?=$row['id']?>">Publish</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>