<div class="container">
    <h1 class="text-center">Add Account</h1>
    <br />
    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <form class="form-horizontal" role="form" method="post" action="/admin/account/<?=$action?>">
                <div class="form-group">
                    <label for="user" class="col-sm-4 control-label">User ID</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="user" name="user" value="<?=isset($user) ? $user : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="group" class="col-sm-4 control-label">Group</label>
                    <div class="col-sm-8">
                        <select class="form-control" name="group">
                            <?php foreach ($groups as $key => $val) { ?>
                                <option value="<?=$key?>" <?=(MySQL_AdminAccountModel::GROUP_DIRECTOR==$key) ? 'selected="selected"' : ''?>><?=$val?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="/admin/account/list" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>