<div class="container">
    <div class="row">
        <div class="col-md-offset-4 col-md-5">
            <div class="panel panel-default" style="margin: 60px auto;">
                <div class="panel-heading">
                    <h3 class="panel-title">Sign in</h3>
                </div>
                <div class="panel-body">
                    <form role="form" method="post" action="/admin/account/signin">
                        <input type="hidden" name="from" id="from" value="<?=isset($from) ? $from : ''?>" />
                        <div class="form-group">
                            <label for="name" class="control-label">Username</label>
                            <input type="text" class="form-control" id="name" name="name" value="<?=isset($name) ? $name : ''?>">
                        </div>
                        <div class="form-group">
                            <label for="password" class="control-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password" value="" />
                        </div>
                        <div class="form-group" id="captcha_row">
                            <label for="captcha_value" class="control-label">Captcha</label>
                            <input type="text" class="form-control" id="captcha_value" name="captcha_value" value="" />
                            <img src="/captcha.php?ns=admin-signin" id="captcha_image" style="cursor: pointer;">
                        </div>
                        <div class="form-group" id="captcha_row">
                            <button type="submit" class="btn btn-default">Sign in</button>
                        </div>
                        <?php if (isset($error)) { ?>
                            <div class="alert alert-danger" role="alert"><?=Misc::escape($error)?></div>
                        <?php } ?>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#name").focus();

        $("#captcha_image").click(function() {
            $(this).attr("src", "").attr("src", "/captcha.php?ns=admin-signin");
        });
    });
</script>