<div class="container">
    <h1 class="text-center">Gift Account List</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
            &nbsp;
        </div>
        <div class="col-md-6">
            <form class="form-inline" role="form" method="get" action="/admin/gift/list">
                <div class="form-group">
                    <label for="user" class="control-label input-sm">User ID</label>
                    <input type="text" name="user" id="user" class="form-control input-sm" value="<?=isset($filter['user']) ? $filter['user'] : ''?>">
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
        <div class="col-md-4">
            <a href="/admin/gift/report_total" class="btn btn-primary" target="_blank">Report Total</a>
            <a href="/admin/gift/get_races" class="btn btn-info" target="_blank">Races</a>
            <a href="/admin/gift/top" class="btn btn-warning" target="_blank">Top</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>User</th>
                    <th>Remaining Gifts</th>
                    <th>Received Gifts</th>
                    <th>Growth Level</th>
                    <th>Growth Points</th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><?=$row['id']?></td>
                        <td><?=$row['collecting']?></td>
                        <td><?=$row['giving']?></td>
                        <td><?=$row['growth_level']?></td>
                        <td><?=$row['growth_points']?></td>
                        <td>
                            <a href="/admin/gift/report_channel?channel=<?=$row['id']?>" class="btn btn-primary btn-sm" target="_blank">Report</a>
                            <a href="/admin/gift/channel_log?channel=<?=$row['id']?>" class="btn btn-info btn-sm" target="_blank">Received Log</a>
                            <a href="/admin/gift/user_log?user=<?=$row['id']?>" class="btn btn-info btn-sm" target="_blank">Collecting Log</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#selectAll").click(function() {
            var checked = $(this).prop("checked");

            $("input[name='ids']").prop("checked", checked);
        });
    });
</script>