<div class="modal fade" id="race-modal" tabindex="-1" role="dialog" aria-labelledby="gift-race" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">New Race</h4>
            </div>
            <div class="modal-body">
                <p>
                    From Date: <input type="text" class="form-control input-sm" id="from-date" name="from-date" value="">
                </p>
                <p>
                    From Time: <input type="text" class="form-control input-sm" id="from-time" name="from-time" value="">
                </p>
                <p>
                    To Date: <input type="text" class="form-control input-sm" id="to-date" name="to-date" value="">
                </p>
                <p>
                    To Time: <input type="text" class="form-control input-sm" id="to-time" name="to-time" value="">
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="save-race">Save</button>
            </div>
        </div>
    </div>
</div>