<div class="container">
    <h1 class="text-center">Collecting Gift Log</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <form class="form-inline" role="form" method="get" action="/admin/gift/user_log">
                <div class="form-group">
                    <label for="user" class="control-label input-sm">User ID</label>
                    <input type="text" name="user" id="user" class="form-control input-sm" value="<?=isset($filter['user']) ? $filter['user'] : ''?>">
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>User</th>
                    <th>Channel</th>
                    <th>Highlight</th>
                    <th>Task</th>
                    <th>Number</th>
                    <th>Dealt On</th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><?=$row['id']?></td>
                        <td><?=$row['user']?></td>
                        <td><?=$row['channel']?></td>
                        <td><?=$row['highlight']?></td>
                        <td><?=$row['task']?></td>
                        <td><?=$row['number']?></td>
                        <td><?=$row['dealt_on'] ? date('Y-m-d H:i:s', $row['dealt_on']) : ''?></td>
                        <td>
                            &nbsp;
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#selectAll").click(function() {
            var checked = $(this).prop("checked");

            $("input[name='ids']").prop("checked", checked);
        });

    });
</script>