<div class="container">
    <h1 class="text-center">Add Game</h1>
    <br />
    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <form class="form-horizontal" role="form" method="post" action="/admin/game/<?=$action?>" enctype="multipart/form-data">
                <input type="hidden" name="id" id="id" value="<?=isset($id) ? $id : ''?>" />
                <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="name" name="name" value="<?=isset($data['name']) ? $data['name'] : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="icon_file" class="col-sm-2 control-label">Icon</label>
                    <div class="col-sm-10">
                        <input type="file" class="form-control" id="icon_file" name="icon_file">
                        <?php if (isset($data['icon']) && $data['icon']) { ?>
                            <img src="https://s3.nikksy.com/<?=$data['icon']?>" class="img-thumbnail" alt="#">
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label for="logo_file" class="col-sm-2 control-label">Logo</label>
                    <div class="col-sm-10">
                        <input type="file" class="form-control" id="logo_file" name="logo_file">
                        <?php if (isset($data['logo']) && $data['logo']) { ?>
                            <img src="https://s3.nikksy.com/<?=$data['logo']?>" class="img-thumbnail" alt="#">
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="/admin/game/list" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>