<div class="container">
    <h1 class="text-center">Edit League Match Schedule</h1>
    <br />
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <form class="form-horizontal" role="form" method="post" action="/admin/leaguematchschedule/<?=$action?>" enctype="multipart/form-data">
                <input type="hidden" name="id" id="id" value="<?=isset($id) ? $id : ''?>" />
                <div class="form-group">
                    <label for="season" class="col-sm-2 control-label">Season</label>
                    <div class="col-sm-10">
                        <select name="season" class="form-control input-sm">
                            <?php foreach ($seasons as $key => $val) { ?>
                                <option value="<?=$val['id']?>" <?=(isset($data['season']) && $val['id']==$data['season']) ? 'selected="selected"' : ''?>><?=Misc::escape($val['title'])?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="title" name="title" value="<?=isset($data['title']) ? Misc::escape($data['title']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="from" class="col-sm-2 control-label">From Date</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="from" name="from" value="<?=isset($data['from']) ? date('Y-m-d', $data['from']) : date('Y-m-d')?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="to" class="col-sm-2 control-label">To Date</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="to" name="to" value="<?=isset($data['to']) ? date('Y-m-d', $data['to']) : date('Y-m-d', strtotime('+7 day'))?>">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="/admin/leaguematchschedule/list" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#from").datepicker({
            changeMonth: true,
            dateFormat: "yy-mm-dd",
            onClose: function(selectedDate) {
                $("#to").datepicker("option", "minDate", selectedDate);
            }
        });

        $("#to").datepicker({
            changeMonth: true,
            dateFormat: "yy-mm-dd",
            onClose: function(selectedDate) {
                $("#from").datepicker("option", "maxDate", selectedDate);
            }
        });
    });
</script>