<div class="container">
    <h1 class="text-center">Streaming Broadcast List</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <form class="form-inline" role="form" method="get" action="/admin/streamingbroadcast/list">
                <div class="form-group">
                    <label for="keyword" class="control-label input-sm">Channel ID</label>
                    <input type="text" name="channel" id="channel" class="form-control input-sm" value="<?=isset($filter['channel']) ? $filter['channel'] : ''?>">
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Channel</th>
                    <th>Title</th>
                    <th>Length</th>
                    <th>Size</th>
                    <th>Views</th>
                    <th>Recording On</th>
                    <th>Ending On</th>
                    <th>Uploaded On</th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><?=$row['id']?></td>
                        <td><?=$row['channel']?></td>
                        <td><?=Misc::escape($row['title'])?></td>
                        <td><?=Misc::formatTimeLength($row['length'])?></td>
                        <td><?=number_format($row['size'])?></td>
                        <td><?=number_format($row['total_views'])?></td>
                        <td><?=$row['recording_on'] ? date('Y-m-d H:i', $row['recording_on']) : ''?></td>
                        <td><?=$row['ending_on'] ? date('Y-m-d H:i', $row['ending_on']) : ''?></td>
                        <td><?=$row['uploaded_on'] ? date('Y-m-d H:i', $row['uploaded_on']) : ''?></td>
                        <td>
                            <a href="/admin/streamingbroadcast/view?broadcast=<?=$row['id']?>" target="_blank" class="btn btn-primary btn-sm">View</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#selectAll").click(function() {
            var checked = $(this).prop("checked");

            $("input[name='ids']").prop("checked", checked);
        });

    });
</script>