<div class="container">
    <h1 class="text-center">View Broadcast Info</h1>
    <br />
    <div class="row">
        <div class="col-md-12">
            <a href="/admin/streamingbroadcast/list" class="btn btn-primary">Broadcast List</a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <tr>
                    <th>Broadcast ID</th>
                    <td><?=isset($data['id']) ? $data['id'] : ''?></td>
                </tr>
                <tr>
                    <th>Channel ID</th>
                    <td><?=isset($data['channel']) ? $data['channel'] : ''?></td>
                </tr>
                <tr>
                    <th>Upstream IP</th>
                    <td><?=isset($data['upstream_ip']) ? Misc::escape($data['upstream_ip']) : ''?></td>
                </tr>
                <tr>
                    <th>Upstream Session</th>
                    <td><?=isset($data['session']) ? Misc::escape($data['session']) : ''?></td>
                </tr>
                <tr>
                    <th>Length</th>
                    <td><?=isset($data['length']) ? Misc::formatTimeLength($data['length']) : ''?></td>
                </tr>
                <tr>
                    <th>Size</th>
                    <td><?=isset($data['size']) ? number_format($data['size']) : ''?></td>
                </tr>
                <tr>
                    <th>Title</th>
                    <td><?=isset($data['title']) ? Misc::escape($data['title']) : ''?></td>
                </tr>
                <tr>
                    <th>Memo</th>
                    <td>
                        <pre><?=isset($data['memo']) ? Misc::escape($data['memo']) : ''?></pre>
                    </td>
                </tr>
                <tr>
                    <th>Recording IP</th>
                    <td><?=isset($data['recording_ip']) ? Misc::escape($data['recording_ip']) : ''?></td>
                </tr>
                <tr>
                    <th>Recording On</th>
                    <td><?=isset($data['recording_on']) && $data['recording_on'] ? date('Y-m-d H:i:s', $data['recording_on']) : ''?></td>
                </tr>
                <tr>
                    <th>Uploaded On</th>
                    <td><?=isset($data['uploaded_on']) && $data['uploaded_on'] ? date('Y-m-d H:i:s', $data['uploaded_on']) : ''?></td>
                </tr>
                <tr>
                    <th>Remote Path</th>
                    <td><?=isset($data['remote_path']) ? Misc::escape($data['remote_path']) : ''?></td>
                </tr>
                <tr>
                    <th>Preview Path</th>
                    <td><?=isset($data['preview_path']) ? Misc::escape($data['preview_path']) : ''?></td>
                </tr>
                <tr>
                    <th>Total Views</th>
                    <td><?=isset($data['total_views']) ? $data['total_views'] : ''?></td>
                </tr>
            </table>
        </div>
    </div>
</div>