<div class="container">
    <h1 class="text-center">Edit Link</h1>
    <br />
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <form class="form-horizontal" role="form" method="post" action="/admin/videolink/<?=$action?>" enctype="multipart/form-data">
                <input type="hidden" name="id" id="id" value="<?=isset($id) ? $id : ''?>" />
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="title" name="title" value="<?=isset($data['title']) ? Misc::escape($data['title']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="url" class="col-sm-2 control-label">URL</label>
                    <div class="col-sm-10">
                        <p class="form-control-static"><?=isset($data['url']) ? $data['url'] : ''?></p>
                    </div>
                </div>
                <div class="form-group">
                    <label for="thumbnail_url" class="col-sm-2 control-label">Thumbnail</label>
                    <div class="col-sm-10">
                        <img src="<?=isset($data['thumbnail_url']) ? $data['thumbnail_url'] : '#'?>" class="img-thumbnail" alt="#">
                    </div>
                </div>
                <div class="form-group">
                    <label for="author_name" class="col-sm-2 control-label">Author</label>
                    <div class="col-sm-10">
                        <p class="form-control-static"><?=isset($data['author_name']) ? Misc::escape($data['author_name']) : ''?></p>
                    </div>
                </div>
                <div class="form-group">
                    <label for="tags" class="col-sm-2 control-label">Tags</label>
                    <div class="col-sm-10">
                        <p class="form-control-static"><?=isset($data['tags']) ? $data['tags'] : ''?></p>
                    </div>
                </div>
                <div class="form-group">
                    <label for="custom_image_file" class="col-sm-2 control-label">Custom Image</label>
                    <div class="col-sm-10">
                        <input type="file" class="form-control" id="custom_image_file" name="custom_image_file">
                        <?php if ($data['custom_image']) { ?>
                        <img src="<?=$data['custom_image']?>" class="img-thumbnail" alt="#">
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label for="created_on" class="col-sm-2 control-label">Created</label>
                    <div class="col-sm-10">
                        <p class="form-control-static">On <?=date('Y-m-d H:i:s', $data['created_on'])?> From <?=$data['ip']?></p>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="/admin/videolink/list" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>