<div class="container">
    <h1 class="text-center">Users</h1>
    <br />
    <div class="row">
        <div class="col-md-12">
            <form class="form-inline" role="form" method="get" action="/admin/user/list">
                <div class="form-group">
                    <select name="search_field" class="form-control input-sm">
                        <option value="name" <?=(isset($filter['search_field']) && 'name'==$filter['search_field']) ? 'selected="selected"' : ''?>>User Name</option>
                        <option value="id" <?=(isset($filter['search_field']) && 'id'==$filter['search_field']) ? 'selected="selected"' : ''?>>User ID</option>
                    </select>
                    <input type="text" name="search_value" class="form-control input-sm" value="<?=isset($filter['search_value']) ? $filter['search_value'] : ''?>">
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>User ID</th>
                    <th>Name</th>
                    <th>Nickname</th>
                    <th>Email</th>
                    <th>Registry Date</th>
                    <th>Banned</th>
                    <th>Operation</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr>
                        <td><?=$row['id']?></td>
                        <td><a href="/admin/user/view?user=<?=$row['id']?>"><?=Misc::escape($row['name'])?></a></td>
                        <td><?=isset($row['nickname']) && $row['nickname'] ? Misc::escape($row['nickname']) : ''?></td>
                        <td><?=Misc::escape($row['email'])?></td>
                        <td><?=isset($row['registered_on']) ? date('Y-m-d H:i', $row['registered_on']) : ''?></td>
                        <td id="banned-<?=$row['id']?>"><?=isset($row['ban_until']) && ($row['ban_until'] > $now) ? 'Y' : ''?></td>
                        <td>
                            <a href="/admin/user/update?user=<?=$row['id']?>" class="btn btn-primary btn-sm">Edit</a>
                            <a href="/admin/user/ban?ids=<?=$row['id']?>&days=<?=isset($row['ban_until']) && ($row['ban_until'] > $now) ? -1 : 14?>" class="btn btn-warning btn-sm btn-ban" data-id="<?=$row['id']?>" data-status="<?=isset($row['ban_until']) && ($row['ban_until'] > $now) ? 1 : 0?>"><?=isset($row['ban_until']) && ($row['ban_until'] > $now) ? 'Release' : 'Ban'?></a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(function() {
        $(".btn-ban").each(function() {
            $(this).click(function() {
                var btn        = $(this),
                    user_id    = btn.data("id"),
                    days       = btn.data("status") ? -1 : 14;

                $.post(
                    "/admin/user/ban",
                    {
                        ids: user_id,
                        days: days
                    },
                    function(response) {
                        if (response.code == 200) {
                            $("#banned-" + user_id).text(days > 0 ? 'Y' : '');
                            btn.data("status", days > 0 ? 1 : 0).text(days > 0 ? "Release" : "Ban");
                        }
                    },
                    "json"
                );

                return false;
            });
        });
    });
</script>