<div class="container">
    <div class="row">
        <div class="col-md-offset-4 col-md-5">
            <div class="panel panel-default" style="margin: 60px auto;">
                <div class="panel-heading">
                    <h3 class="panel-title">Sign in</h3>
                </div>
                <div class="panel-body">
                    <form role="form" method="post" action="/admin/user/login">
                        <input type="hidden" name="from" id="from" value="<?=isset($from) ? $from : ''?>" />
                        <div class="form-group">
                            <label for="username" class="control-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" value="<?=isset($username) ? $username : ''?>">
                        </div>
                        <div class="form-group">
                            <label for="password" class="control-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password" value="" />
                        </div>
                        <button type="submit" class="btn btn-default">Sign in</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#username").focus();
    });
</script>