<div class="container">
    <h1 class="text-center">View User Info</h1>
    <br />
    <div class="row">
        <div class="col-md-12">
            <a href="/admin/user/list" class="btn btn-primary">User List</a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <tr>
                    <th>User ID</th>
                    <td><?=isset($data['id']) ? $data['id'] : ''?></td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td><?=isset($data['name']) ? Misc::escape($data['name']) : ''?></td>
                </tr>
                <tr>
                    <th>Nickname</th>
                    <td><?=isset($data['nickname']) ? Misc::escape($data['nickname']) : ''?></td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td><?=isset($data['email']) ? $data['email'] : ''?></td>
                </tr>
                <tr>
                    <th>Birthday</th>
                    <td><?=isset($data['birthday']) ? $data['birthday'] : ''?></td>
                </tr>
                <tr>
                    <th>Lang</th>
                    <td><?=isset($data['lang']) ? $data['lang'] : ''?></td>
                </tr>
                <tr>
                    <th>Registered</th>
                    <td><?=sprintf('%s (%s)', $data['registered_ip'], date('Y-m-d H:i', $data['registered_on']))?></td>
                </tr>
            </table>
        </div>
    </div>
</div>