<div class="container">
    <h1 class="text-center">Gold Account List</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <form class="form-inline" role="form" method="get" action="/admin/gold/list">
                <div class="form-group">
                    <label for="user" class="control-label input-sm">User ID</label>
                    <input type="text" name="user" id="user" class="form-control input-sm" value="<?=isset($filter['user']) ? $filter['user'] : ''?>">
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>User</th>
                    <th>Recharge Num.</th>
                    <th>Recharge Times</th>
                    <th>Earn Num.</th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><?=$row['id']?></td>
                        <td><?=$row['recharge_num']?></td>
                        <td><?=$row['recharge_times']?></td>
                        <td><?=$row['earn_num']?></td>
                        <td>
                            <a href="/admin/gold/recharge?user=<?=$row['id']?>" class="btn btn-info btn-sm btn-recharge" data-id="<?=$row['id']?>">Recharge</a>
                            <a href="/admin/gold/log?user=<?=$row['id']?>" target="_blank" class="btn btn-primary btn-sm">Log</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php include Yaf_View_Simple::getScriptPath() . DIRECTORY_SEPARATOR . 'gold' . DIRECTORY_SEPARATOR . 'modal-recharge.phtml'; ?>

<script>
    $(function() {
        $("#selectAll").click(function() {
            var checked = $(this).prop("checked");

            $("input[name='ids']").prop("checked", checked);
        });

        $(".btn-recharge").each(function() {
            $(this).click(function() {
                var btn = $(this),
                    id  = btn.data("id");

                $("#recharge-user").val(id + "");

                $("#recharge-modal").modal("show");

                return false;
            });
        });

        $("#submit-recharge").click(function() {
            var user = $("#recharge-user").val(),
                golds = $("#recharge-golds").val();

            $.post(
                "/admin/gold/recharge",
                {
                    user: user,
                    golds: golds
                },
                function(response) {
                    if (response.code == 200) {
                        window.alert(response.message);

                        window.location.reload();
                    } else {
                        window.alert(response.message ? response.message : "Failed");
                    }
                },
                "json"
            );

            $("#recharge-modal").modal("hide");
        });
    });
</script>