<div class="modal fade" id="recharge-modal" tabindex="-1" role="dialog" aria-labelledby="recharge" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Recharge User</h4>
            </div>
            <div class="modal-body">
                <p>
                    User ID: <input type="text" class="form-control input-sm" id="recharge-user" name="recharge-user" value="">
                </p>
                <p>
                    Golds: <input type="text" class="form-control input-sm" id="recharge-golds" name="recharge-golds" value="">
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="submit-recharge">Submit</button>
            </div>
        </div>
    </div>
</div>