<div class="container">
    <h1 class="text-center">Recharge Order List</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <form class="form-inline" role="form" method="get" action="/admin/gold/recharge_orders">
                <div class="form-group">
                    <label for="user" class="control-label input-sm">User ID</label>
                    <input type="text" name="user" id="user" class="form-control input-sm" value="<?=isset($filter['user']) ? $filter['user'] : ''?>">
                </div>
                <div class="form-group">
                    <label for="status" class="control-label input-sm">Status</label>
                    <select name="status" class="form-control input-sm">
                        <option value="is_processed" <?=(isset($filter['status']) && 'is_processed'==$filter['status']) ? 'selected="selected"' : ''?>>Purchased</option>
                        <option value="is_bad" <?=(isset($filter['status']) && 'is_bad'==$filter['status']) ? 'selected="selected"' : ''?>>Bad</option>
                        <option value="is_pending" <?=(isset($filter['status']) && 'is_pending'==$filter['status']) ? 'selected="selected"' : ''?>>Pending</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>User</th>
                    <th>Foreign ID</th>
                    <th>Golds</th>
                    <th>Cost</th>
                    <th>Created On</th>
                    <th>Status</th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><?=$row['id']?></td>
                        <td><?=$row['user']?></td>
                        <td><?=$row['foreign_id']?></td>
                        <td><?=$row['golds']?></td>
                        <td><?=$row['cost']?></td>
                        <td><?=$row['processed_on'] ? date('Y-m-d H:i', $row['processed_on']) : ''?></td>
                        <td>
                            <?php if ($row['is_processed'] == MySQL_Gold_RechargeOrderModel::PROCESSED_STATUS_PURCHASED) { ?>
                                <span class="label label-success">Purchased</span>
                            <?php } else if ($row['is_processed'] == MySQL_Gold_RechargeOrderModel::PROCESSED_STATUS_CANCELLED) { ?>
                                <span class="label label-default">Cancelled</span>
                            <?php } ?>
                            <?php if ($row['is_bad']) { ?>
                                <span class="label label-danger">Bad</span>
                            <?php } ?>
                        </td>
                        <td>
                            <a href="/admin/gold/view_recharge_order?id=<?=$row['id']?>" target="_blank" class="btn btn-primary btn-sm">View</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#selectAll").click(function() {
            var checked = $(this).prop("checked");

            $("input[name='ids']").prop("checked", checked);
        });
    });
</script>