<div class="container">
    <h1 class="text-center">Edit Watching Task</h1>
    <br />
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <form class="form-horizontal" role="form" method="post" action="/admin/streamingwatchingtask/<?=$action?>" enctype="multipart/form-data">
                <input type="hidden" name="id" id="id" value="<?=isset($id) ? $id : ''?>" />
                <div class="form-group">
                    <label for="level" class="col-sm-2 control-label">Level</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="level" name="level" value="<?=isset($data['level']) ? $data['level'] : 0?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="gifts" class="col-sm-2 control-label">Gifts</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="gifts" name="gifts" value="<?=isset($data['gifts']) ? $data['gifts'] : 0?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="points" class="col-sm-2 control-label">Points</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="points" name="points" value="<?=isset($data['points']) ? $data['points'] : 0?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="timer" class="col-sm-2 control-label">Timer</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="timer" name="timer" value="<?=isset($data['timer']) ? $data['timer'] : 0?>">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="/admin/streamingwatchingtask/list" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>