<div class="container">
    <h1 class="text-center">Streaming Supervisor List</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
            &nbsp;
        </div>
        <div class="col-md-10">
            <form class="form-inline" role="form" method="get" action="/admin/streamingeditor/list">
                <div class="form-group">
                    <label for="user" class="control-label input-sm">User ID</label>
                    <input type="text" name="user" id="user" class="form-control input-sm" >
                </div>
                <button type="button" class="btn btn-default btn-sm" id="btn-add">Add</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th><input type="checkbox" class="multi-select" name="selectAll" id="selectAll"></th>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Created on</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><input type="checkbox" class="multi-select" name="ids" value="1" data-id="<?=$row['id']?>"></td>
                        <td><?=$row['id']?></td>
                        <td><?=Misc::escape($row['name'])?></td>
                        <td><?=date('Y-m-d H:i', $row['created_on'])?></td>
                        <td>
                            <a href="/admin/streamingsupervisor/delete?ids=<?=$row['id']?>" class="btn btn-danger btn-sm btn-delete" data-id="<?=$row['id']?>">Delete</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#selectAll").click(function() {
            var checked = $(this).prop("checked");

            $("input[name='ids']").prop("checked", checked);
        });

        $(".btn-delete").each(function() {
            $(this).click(function() {
                if (window.confirm('Really???')) {
                    var btn = $(this),
                        id  = btn.data("id");

                    $.post(
                        "/admin/streamingsupervisor/delete",
                        {
                            ids: id
                        },
                        function(response) {
                            if (response.code == 200) {
                                $("#row-" + id).remove();
                            }
                        },
                        "json"
                    );
                }

                return false;
            });
        });

        $("#btn-add").click(function() {
            $.post(
                "/admin/streamingsupervisor/add",
                {
                    user: $("#user").val()
                },
                function(response) {
                    if (response.code == 200) {
                        window.alert(response.message);

                        window.location.reload();
                    } else {
                        window.alert(response.message ? response.message : "Failed");
                    }
                },
                "json"
            );

            return false;
        });
    });
</script>