<div class="container">
    <h1 class="text-center">Channel Class List</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
            <a href="/admin/streamingchannelclass/create" class="btn btn-primary">New</a>
        </div>
        <div class="col-md-10">
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Level</th>
                    <th>Title</th>
                    <th>Hourly Pay</th>
                    <th>Exclusive Bonus</th>
                    <th>Withdraw Rate</th>
                    <th>Created On</th>
                    <th>Operation</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><?=$row['id']?></td>
                        <td><?=$row['level']?></td>
                        <td><?=Misc::escape($row['title'])?></td>
                        <td><?=$row['hourly_pay']?></td>
                        <td><?=$row['exclusive_bonus']?></td>
                        <td><?=$row['withdraw_rate']?></td>
                        <td><?=date('Y-m-d H:i', $row['created_on'])?></td>
                        <td>
                            <a href="/admin/streamingchannelclass/update?id=<?=$row['id']?>" class="btn btn-primary btn-sm">Edit</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
