<div class="container">
    <h1 class="text-center">Edit Video Room</h1>
    <br />
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <form class="form-horizontal" role="form" method="post" action="/admin/videoroom/<?=$action?>">
                <div class="form-group">
                    <label for="id" class="col-sm-2 control-label">Room ID</label>
                    <div class="col-sm-10">
                        <?php if (isset($data['id'])) { ?>
                        <input type="hidden" name="id" id="id" value="<?=isset($id) ? $id : ''?>" />
                        <p class="form-control-static"><?=isset($data['id']) ? $data['id'] : ''?></p>
                        <?php } else { ?>
                        <input type="text" class="form-control" id="id" name="id" value="">
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="title" name="title" value="<?=isset($data['title']) ? Misc::escape($data['title']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="bio" class="col-sm-2 control-label">Bio</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="bio" name="bio" rows="5"><?=isset($data['bio']) ? Misc::escape($data['bio']) : ''?></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="<?=$_SERVER['HTTP_REFERER'] ?: '/admin/videoroom/list'?>" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>