<div class="container">
    <h1 class="text-center">Video Room List</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
            <a href="/admin/videoroom/create" class="btn btn-primary">New</a>
        </div>
        <div class="col-md-10">
            <form class="form-inline" role="form" method="get" action="/admin/videoroom/list">
                <div class="form-group">
                    <label for="keyword" class="control-label input-sm">Room ID</label>
                    <input type="text" name="room" id="room" class="form-control input-sm" value="<?=isset($filter['room']) ? $filter['room'] : ''?>">
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Bio</th>
                    <th>Stream Key</th>
                    <th>Created on</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><?=$row['id']?></td>
                        <td><?=Misc::escape($row['title'])?></td>
                        <td>
                            <pre>
                                <?=Misc::escape($row['bio'])?>
                            </pre>
                        </td>
                        <td><?=Misc::escape($row['stream_key'])?></td>
                        <td><?=date('Y-m-d H:i', $row['created_on'])?></td>
                        <td>
                            <a href="/admin/videoroom/update?id=<?=$row['id']?>" class="btn btn-primary btn-sm">Edit</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#selectAll").click(function() {
            var checked = $(this).prop("checked");

            $("input[name='ids']").prop("checked", checked);
        });

        $(".btn-delete").each(function() {
            $(this).click(function() {
                if (window.confirm('Really???')) {
                    var btn = $(this),
                        id  = btn.data("id");

                    $.post(
                        "/admin/videolink/delete",
                        {
                            ids: id
                        },
                        function(response) {
                            if (response.code == 200) {
                                $("#row-" + id).remove();
                            }
                        },
                        "json"
                    );
                }

                return false;
            });
        });
    });
</script>