<header class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/admin" class="navbar-brand">LNPLAY</a>
        </div>
        <nav class="collapse navbar-collapse" role="navigation">
            <?php if (isset(Yaf_Session::getInstance()->admin)) { ?>
                <ul class="nav navbar-nav nav-pills">
                    <?php if (Yaf_Session::getInstance()->admin['group'] <= MySQL_AdminAccountModel::GROUP_ADMIN) { ?>
                        <li class="dropdown">
                            <a id="dropdown-menu-administration" class="dropdown-toggle" data-toggle="dropdown" href="#administration">Administration <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdown-menu-administration">
                                <li>
                                    <a href="/admin/account/list">Account</a>
                                </li>
                                <?php if (Yaf_Session::getInstance()->admin['group'] <= MySQL_AdminAccountModel::GROUP_SUPER_ADMIN) { ?>
                                    <li>
                                        <a href="/admin/log/list">Log</a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                        <li>
                            <a id="dropdown-menu-hearthstone" class="dropdown-toggle" data-toggle="dropdown" href="#hearthstone">Hearthstone <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdown-menu-hearthstone">
                                <li class="dropdown-header">Deck</li>
                                <li>
                                    <a href="/admin/deck/list">Deck Store</a>
                                </li>
                                <li>
                                    <a href="/admin/recommended/list">Editor Recommended</a>
                                </li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Card</li>
                                <li>
                                    <a href="/admin/card/list">Card List</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a id="dropdown-menu-lol" class="dropdown-toggle" data-toggle="dropdown" href="#lol">League of Legends <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdown-menu-lol">
                                <li class="dropdown-header">Champion</li>
                                <li>
                                    <a href="/admin/lolchampion/weeklyreport">Weekly Report</a>
                                </li>
                                <li>
                                    <a href="/admin/lolchampion/monthlyreport">Monthly Report</a>
                                </li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Summoner</li>
                                <li>
                                    <a href="/admin/lolsummoner/search">Search</a>
                                </li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Original</li>
                                <li>
                                    <a href="/admin/loloriginal/champions">Champions</a>
                                    <a href="/admin/loloriginal/abilities">Abilities</a>
                                    <a href="/admin/loloriginal/items">Items</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a id="dropdown-menu-user" class="dropdown-toggle" data-toggle="dropdown" href="#user">User <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdown-menu-user">
                                <li>
                                    <a href="/admin/mkuser/list">List</a>
                                </li>
                                <!--li class="dropdown-header">Charts</li>
                                <li>
                                    <a href="/admin/report/summary">Summary</a>
                                </li>
                                <li class="divider"></li-->
                                <li class="dropdown-header">Registration</li>
                                <li>
                                    <a href="/admin/report/regdaily">Daily</a>
                                </li>
                                <li>
                                    <a href="/admin/report/regweekly">Weekly</a>
                                </li>
                                <li>
                                    <a href="/admin/report/regmonthly">Monthly</a>
                                </li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Active Users</li>
                                <!--li>
                                    <a href="/admin/report/dau">Daily</a>
                                </li-->
                                <li>
                                    <a href="/admin/report/mau">Monthly</a>
                                </li>
                                <!--li class="divider"></li>
                                <li>
                                    <a href="/admin/report/ou">Online Users</a>
                                </li-->
                            </ul>
                        </li>
                    <?php } ?>
                    <?php if (Yaf_Session::getInstance()->admin['group'] <= MySQL_AdminAccountModel::GROUP_DIRECTOR) { ?>
                        <li>
                            <a id="dropdown-menu-video" class="dropdown-toggle" data-toggle="dropdown" href="#video">Video <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdown-menu-video">
                                <li class="dropdown-header">Link</li>
                                <li>
                                    <a href="/admin/videolink/list">List</a>
                                </li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Comment</li>
                                <li>
                                    <a href="/admin/videocomment/list">List</a>
                                </li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Bullet</li>
                                <li>
                                    <a href="/admin/videobullet/list">List</a>
                                </li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Tag</li>
                                <li>
                                    <a href="/admin/videotaggroup/list">Group List</a>
                                </li>
                                <li>
                                    <a href="/admin/videotag/list">List</a>
                                </li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Column</li>
                                <li>
                                    <a href="/admin/videocolumn/list">Column List</a>
                                    <a href="/admin/videolinkcolumn/list">Link List</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a id="dropdown-menu-streaming" class="dropdown-toggle" data-toggle="dropdown" href="#streaming">Streaming <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdown-menu-streaming">
                                <li class="dropdown-header">Channel</li>
                                <li>
                                    <a href="/admin/streamingchannel/list">List</a>
                                </li>
                                <li>
                                    <a href="/admin/streamingeditor/list">Editor</a>
                                </li>
                                <li>
                                    <a href="/admin/streamingblacklist/list">Blacklist</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a id="dropdown-menu-misc" class="dropdown-toggle" data-toggle="dropdown" href="#misc">Misc <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdown-menu-misc">
                                <li>
                                    <a href="/admin/feedback/summary">Feedback</a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="/admin/badword/list">Badword</a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="/admin/reported/list">Report</a>
                                </li>
                                <?php if (Yaf_Session::getInstance()->admin['group'] <= MySQL_AdminAccountModel::GROUP_ADMIN) { ?>
                                <li class="divider"></li>
                                <li>
                                    <a href="/admin/announcement/list">Announcement</a>
                                </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/admin/user/logout">Logout</a>
                    </li>
                </ul>
            <?php } ?>
        </nav>
    </div>
</header>