<header class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">NIKKSY</a>
        </div>
        <nav class="collapse navbar-collapse" role="navigation">
            <ul class="nav navbar-nav nav-pills">
                <li>
                    <a href="/passport/test/signup">Sign up</a>
                </li>
                <li>
                    <a href="/passport/test/signin">Sign in</a>
                </li>
                <li>
                    <a href="/passport/test/profile">Profile</a>
                </li>
                <li>
                    <a href="/passport/test/changepassword">Change password</a>
                </li>
                <li>
                    <a href="/passport/test/reset">Find password</a>
                </li>
                <li>
                    <a href="/passport/test/forgotname">Forgot username</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="/passport/user/signout?from=/passport/test/signin">Sign out</a>
                </li>
            </ul>
        </nav>
    </div>
</header>