<div class="container">
    <h1 class="text-center">Card List</h1>
    <br />
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Card ID</th>
                    <th>Card Name</th>
                    <th>Rarity</th>
                    <th>Card Type</th>
                    <th>Cost</th>
                    <th>Attack</th>
                    <th>Health</th>
                    <th>Class</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr>
                        <td><?=$row['id']?></td>
                        <td><?=$row['card_id']?></td>
                        <td><?=$row['name']?></td>
                        <td><?=$row['rarity']?></td>
                        <td><?=$row['type']?></td>
                        <td><?=$row['cost']?></td>
                        <td><?=$row['attack']?></td>
                        <td><?=$row['health']?></td>
                        <td><?=$row['class']?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>