<div class="container">
    <h1 class="text-center">Edit Time Card Type</h1>
    <br />
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <form class="form-horizontal" role="form" method="post" action="/admin/timecardtype/<?=$action?>" enctype="multipart/form-data">
                <input type="hidden" name="id" id="id" value="<?=isset($id) ? $id : ''?>" />
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="title" name="title" value="<?=isset($data['title']) ? Misc::escape($data['title']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="price" class="col-sm-2 control-label">Price</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="price" name="price" value="<?=isset($data['price']) ? Misc::escape($data['price']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="game" class="col-sm-2 control-label">Game</label>
                    <div class="col-sm-10">
                        <select name="game" class="form-control">
                            <?php foreach ($games as $game) { ?>
                            <option value="<?=$game['id']?>" <?php if (isset($data['game']) && ($data['game'] == $game['id'])) { ?> selected="selected"<?php } ?>><?=Misc::escape($game['name'])?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="/admin/timecardtype/list" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>