<div class="container">
    <div class="row">
        <div class="col-md-offset-4 col-md-5">
            <div class="panel panel-default" style="margin: 60px auto;">
                <div class="panel-heading">
                    <h3 class="panel-title">Change your password</h3>
                </div>
                <div class="panel-body">
                    <form role="form" method="post" id="changepasswordform">
                        <div class="form-group">
                            <label for="old_password" class="control-label">Old Password</label>
                            <input type="password" class="form-control" id="old_password" name="old_password" value="" />
                        </div>
                        <div class="form-group">
                            <label for="new_password" class="control-label">New Password</label>
                            <input type="password" class="form-control" id="new_password" name="new_password" value="" />
                        </div>
                        <div class="form-group">
                            <label for="new_password_confirm" class="control-label">Verify Password</label>
                            <input type="password" class="form-control" id="new_password_confirm" name="new_password_confirm" value="" />
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-default">Set Password</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <pre id="result"></pre>
    </div>
</div>

<script>
    $(function() {
        $("#old_password").focus();

        $("#changepasswordform").submit(function() {
            var old_password = $("#old_password").val(),
                new_password = $("#new_password").val(),
                new_password_confirm = $("#new_password_confirm").val();

            $.post(
                '/passport/user/update_password',
                {
                    old_password: old_password,
                    new_password: new_password,
                    new_password_confirm: new_password_confirm
                },
                function(res) {
                    if (res.code == 200) {
//                        window.location.href = '/passport/test/profile';
                    }

                    $("#result").text(JSON.stringify(res));
                    alert(JSON.stringify(res));
                },
                'json'
            );

            return false;
        });
    });
</script>