<div class="container">
    <div class="row">
        <div class="col-md-offset-4 col-md-5">
            <div class="panel panel-default" style="margin: 60px auto;">
                <div class="panel-heading">
                    <h3 class="panel-title">Sign up</h3>
                </div>
                <div class="panel-body">
                    <form role="form" method="post" id="signupwithfacebookform">
                        <input type="hidden" name="from" id="from" value="<?=isset($from) ? $from : ''?>" />
                        <div class="form-group">
                            <label for="name" class="control-label">Username</label>
                            <input type="text" class="form-control" id="name" name="name" value="<?=isset($name) ? $name : ''?>">
                        </div>
                        <div class="form-group">
                            <label for="password" class="control-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password" value="" />
                        </div>
                        <button type="submit" class="btn btn-default">Sign up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <pre id="result"></pre>
    </div>
</div>

<script>
    $(function() {
        $("#username").focus();

        $("#signupwithfacebookform").submit(function() {
            var name = $("#name").val(),
                password = $("#password").val();

            $.post(
                '/passport/user/signup_with_facebook',
                {
                    name: name,
                    password: password
                },
                function(res) {
                    if (res.code == 200) {
//                        window.location.href = '/passport/test/profile';
                    }

                    $("#result").text(JSON.stringify(res));
                    alert(JSON.stringify(res));
                },
                'json'
            );

            return false;
        });
    });
</script>