<div class="container">
    <h1 class="text-center">Edit Column</h1>
    <br />
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <form class="form-horizontal" role="form" method="post" action="/admin/streamingcolumn/<?=$action?>" enctype="multipart/form-data">
                <input type="hidden" name="id" id="id" value="<?=isset($id) ? $id : ''?>" />
                <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="name" name="name" value="<?=isset($data['name']) ? Misc::escape($data['name']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="description" class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="description" name="description" rows="5"><?=isset($data['description']) ? Misc::escape($data['description']) : ''?></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="/admin/streamingcolumn/list" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>