<div class="container">
    <h1 class="text-center">Column List</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
            <a href="/admin/streamingcolumn/create" class="btn btn-primary">New</a>
        </div>
        <div class="col-md-10">
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Operation</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><?=$row['id']?></td>
                        <td><a href="/admin/streamingcolumnitem/list?column=<?=$row['id']?>"><?=Misc::escape($row['name'])?></a></td>
                        <td>
                            <a href="/admin/streamingcolumn/update?id=<?=$row['id']?>" class="btn btn-primary btn-sm">Edit</a>
                            <a href="/admin/streamingcolumn/delete?ids=<?=$row['id']?>" class="btn btn-danger btn-sm btn-delete" data-id="<?=$row['id']?>">Delete</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(function() {
        $(".btn-delete").each(function() {
            $(this).click(function() {
                if (window.confirm('Really???')) {
                    var btn = $(this),
                        id  = btn.data("id");

                    $.post(
                        "/admin/streamingcolumn/delete",
                        {
                            ids: id
                        },
                        function(response) {
                            if (response.code == 200) {
                                $("#row-" + id).remove();
                            }
                        },
                        "json"
                    );
                }

                return false;
            });
        });
    });
</script>