<div class="container">
    <h1 class="text-center">Streaming Campaign Members</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
            &nbsp;
        </div>
        <div class="col-md-10">
            <form class="form-inline" role="form" method="get" action="/admin/streamingcampaignmember/list">
                <div class="form-group">
                    <select name="search_field" class="form-control input-sm">
                        <option value="name" <?=(isset($filter['search_field']) && 'name'==$filter['search_field']) ? 'selected="selected"' : ''?>>User Name</option>
                        <option value="id" <?=(isset($filter['search_field']) && 'id'==$filter['search_field']) ? 'selected="selected"' : ''?>>User ID</option>
                    </select>
                    <input type="text" name="search_value" class="form-control input-sm" value="<?=isset($filter['search_value']) ? $filter['search_value'] : ''?>">
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Game Account</th>
                    <th>Memo</th>
                    <th>Contact</th>
                    <th>Status</th>
                    <th>Signed on</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>" class="<?=$row['is_online'] ? 'success' : ''?>">
                        <td><a href="/admin/streamingchannel/view?channel=<?=$row['id']?>"><?=$row['id']?></a></td>
                        <td><?=Misc::escape($row['name'])?></td>
                        <td><?=Misc::escape($row['game_account'])?></td>
                        <td>
                            <div style="width: 190px; height:80px; overflow: auto;">
                                <pre id="memo-<?=$row['id']?>"><?=Misc::escape($row['memo'])?></pre>
                            </div>
                        </td>
                        <td>
                            <ul class="list-unstyled">
                                <?php if ($row['facebook']) { ?>
                                <li><strong>Facebook:</strong><span class="pull-right"><?=Misc::escape($row['facebook'])?></span></li>
                                <?php } ?>
                                <?php if ($row['skype']) { ?>
                                <li><strong>Skype:</strong><span class="pull-right"><?=Misc::escape($row['skype'])?></span></li>
                                <?php } ?>
                            </ul>
                        </td>
                        <td>
                            <?php if ($row['is_online']) { ?>
                                <span class="label label-success">Live</span>
                            <?php } ?>
                        </td>
                        <td><?=date('Y-m-d H:i', $row['signed_on'])?></td>
                        <td>
                            <a href="/admin/streamingchannel/history?channel=<?=$row['id']?>" class="btn btn-info btn-sm btn-history" target="_blank">History</a>
                            <button type="button" class="btn btn-warning btn-sm btn-memo" data-id="<?=$row['id']?>">Memo</button>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php include Yaf_View_Simple::getScriptPath() . DIRECTORY_SEPARATOR . 'streamingchannel' . DIRECTORY_SEPARATOR . 'modal-memo.phtml'; ?>

<script>
    $(function() {
        $("#selectAll").click(function() {
            var checked = $(this).prop("checked");

            $("input[name='ids']").prop("checked", checked);
        });

        $(".btn-memo").each(function() {
            $(this).click(function() {
                var btn = $(this),
                    id  = btn.data("id");

                $("#input-channel-memo").val($("#memo-"+id).text());
                $("#memo-channel").val(id);

                $("#memo-modal").modal("show");

                return false;
            });
        });

        $("#save-memo").click(function() {
            var id = $("#memo-channel").val(),
                memo = $("#input-channel-memo").val();

            $.post(
                "/admin/streamingchannel/memo",
                {
                    id: id,
                    memo: memo
                },
                function(response) {
                    if (response.code == 200) {
                        $("#memo-"+id).text(memo);
                    } else {
                        window.alert("Failed");
                    }
                },
                "json"
            );

            $("#memo-modal").modal("hide");
        });

//        $(".btn-memo").each(function() {
//            $(this).click(function() {
//                var btn = $(this),
//                    id  = btn.data("id"),
//                    memo = $("#memo-"+id);
//
//                var input = window.prompt('Memo', memo.text());
//
//                if (input != null) {
//                    $.post(
//                        "/admin/streamingcampaignmember/memo",
//                        {
//                            id: id,
//                            memo: input
//                        },
//                        function(response) {
//                            if (response.code == 200) {
//                                memo.text(input);
//                            } else {
//                                window.alert("Failed");
//                            }
//                        },
//                        "json"
//                    );
//                }
//
//                return false;
//            });
//        });
    });
</script>