<div class="container">
    <h1 class="text-center">Edit Streaming Server</h1>
    <br />
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <form class="form-horizontal" role="form" method="post" action="/admin/streamingserver/<?=$action?>" enctype="multipart/form-data">
                <input type="hidden" name="id" id="id" value="<?=isset($id) ? $id : ''?>" />
                <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="name" name="name" value="<?=isset($data['name']) ? Misc::escape($data['name']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="ip" class="col-sm-2 control-label">IP</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="ip" name="ip" value="<?=isset($data['ip']) ? Misc::escape($data['ip']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="port" class="col-sm-2 control-label">Port</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="port" name="port" value="<?=isset($data['port']) ? Misc::escape($data['port']) : ''?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="weight" class="col-sm-2 control-label">Weight</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="weight" name="weight" value="<?=isset($data['weight']) ? Misc::escape($data['weight']) : ''?>">
                    </div>
                    <p class="col-sm-4 form-control-static">(Max 10)</p>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="<?=$_SERVER['HTTP_REFERER'] ?: '/admin/streamingserver/list'?>" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>