<div class="container">
    <h1 class="text-center">Time Card Exchange Requests</h1>
    <br />
    <div class="row">
        <div class="col-md-2">
            &nbsp;
        </div>
        <div class="col-md-10">
            <form class="form-inline" role="form" method="get" action="/admin/timecardrequest/list">
                <div class="form-group">
                    <label for="user" class="control-label input-sm">User</label>
                    <input type="text" name="user" id="user" class="form-control input-sm" value="<?=isset($filter['user']) ? $filter['user'] : ''?>">
                </div>
                <button type="submit" class="btn btn-default btn-sm">Query</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php include Yaf_Registry::get('layout')->getPath() . DIRECTORY_SEPARATOR . 'paginator.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>User</th>
                    <th>Type</th>
                    <th>Created On</th>
                    <th>Processed On</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $row) { ?>
                    <tr id="row-<?=$row['id']?>">
                        <td><?=$row['id']?></td>
                        <td><?=$row['user']?></td>
                        <td><?=Misc::escape($row['title'])?></td>
                        <td><?=$row['created_on'] ? date('Y-m-d H:i', $row['created_on']) : ''?></td>
                        <td><?=$row['processed_on'] ? date('Y-m-d H:i', $row['processed_on']) : ''?></td>
                        <td>
                            <a href="/admin/timecardrequest/view?id=<?=$row['id']?>" target="_blank" class="btn btn-primary btn-sm">View</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#selectAll").click(function() {
            var checked = $(this).prop("checked");

            $("input[name='ids']").prop("checked", checked);
        });
    });
</script>