<div class="modal fade" id="modify-teams-modal" tabindex="-1" role="dialog" aria-labelledby="modify-teams" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Modify Teams</h4>
            </div>
            <div class="modal-body">
                <p>
                    <textarea id="input-teams-memo" name="input-teams-memo" class="form-control" rows="8"></textarea>
                </p>
                <input type="hidden" id="input-app-id" name="input-app-id" value="">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="submit-modify">Submit</button>
            </div>
        </div>
    </div>
</div>